# Tomcat
server:
  tomcat:
      uri-encoding: UTF-8
      max-threads: 1000
      min-spare-threads: 30
  port: 8090
  context-path: /
# mysql
spring:
  datasource:
    dynamic:
      primary: gen
      datasource:
        # 代码生成器数据源 扫描&导出工具数据源
        gen:
          driver-class-name: com.mysql.jdbc.Driver
          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
          username: ${SPRING_DATASOURCE_USERNAME:hzero}
          password: ${SPRING_DATASOURCE_PASSWORD:hzero}
        # 开发环境
        dev:
          driver-class-name: com.mysql.jdbc.Driver
          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
          username: ${SPRING_DATASOURCE_USERNAME:root}
          password: ${SPRING_DATASOURCE_PASSWORD:root}
#          driver-class-name: com.mysql.jdbc.Driver
#          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://172.23.16.44:3311?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
#          username: ${SPRING_DATASOURCE_USERNAME:root}
#          password: ${SPRING_DATASOURCE_PASSWORD:Root@123!}
        # 测试环境
        tst:
          driver-class-name: oracle.jdbc.driver.OracleDriver
          url: ${SPRING_DATASOURCE_URL:jdbc:oracle:thin:@172.20.0.203:1521:XE}
          username: ${SPRING_DATASOURCE_USERNAME:hzero}
          password: ${SPRING_DATASOURCE_PASSWORD:hzero}
        # 验收环境
        uat:
#          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#          url: ${SPRING_DATASOURCE_URL:jdbc:sqlserver://172.23.16.42:1433;}
#          username: ${SPRING_DATASOURCE_USERNAME:SA}
#          password: ${SPRING_DATASOURCE_PASSWORD:Admin@12345!}
          driver-class-name: org.postgresql.Driver
          url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://172.23.16.42:5432/hzero}
          username: ${SPRING_DATASOURCE_USERNAME:postgres}
          password: ${SPRING_DATASOURCE_PASSWORD:123456}
        # 生产环境
        prd:
          driver-class-name: com.mysql.jdbc.Driver
          url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306?useUnicode=true&characterEncoding=UTF-8&useSSL=false}
          username: ${SPRING_DATASOURCE_USERNAME:hzero}
          password: ${SPRING_DATASOURCE_PASSWORD:hzero}
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss
  resources:
          static-locations: classpath:/static/,classpath:/view/

# Mybatis配置
mybatis:
  mapperLocations: classpath:mapper/**/*.xml

liquibase:
  enabled: false
  exclusion: hpfm_config,iam_role,fd_organization,iam_user,hiam_user_info,iam_member_role,oauth_client,oauth_ldap,oauth_password_policy,hpfm_permission_rule,hpfm_permission_rel,hpfm_config,hpfm_code_rule,hpfm_code_rule,hpfm_code_rule_detail,hpfm_static_text,hpfm_static_text_value,hpfm_tenant,hpfm_group,hmsg_email_server,hmsg_email_property,hmsg_sms_server,hmsg_receive_config,hmsg_receiver_type,hmsg_message_template.template_content,hmsg_message_template.external_code

scan:
  tool:
    # 临时表所在库
    temporary: hzero_generator
    # 权限表所在库
    permission: hzero_platform
    # 服务路由表所在库
    service: hzero_admin

hzero:
  file:
    token-url: http://hzeronb.saas.hand-china.com/hfle/v1/0/files/signedUrl
    access-token: fa1611d7-fee5-4fad-976d-1e8fb12ef5d0
